# https://medium.com/devops-techable/build-docker-image-with-github-actions-and-push-it-to-amazon-ecr-d4e739472284

name: Deploy to ECR

on:
  push:
    branches: 
     - 'main'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
     - name: Check out code
       uses: actions/checkout@v2

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-west-2

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1

     - name: Build, tag, and push image to Amazon ECR
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         ECR_REPOSITORY: booking-movie-ticket
         IMAGE_TAG: booking-movie-ticket-image-${{github.run_number}}
       run: |
         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

     - name: Deploy Container
       uses: fjogeleit/http-request-action@v1
       with:
         url: 'https://thisper.levantine.io/build'
         method: 'POST'
         customHeaders: '{"Content-Type": "application/json"}'
         data: '{"job_id": "Deploy-booking-movie-ticket", "auth_key": "${{ secrets.jenkins_token }}"}'